name: cast
description: Dart package to discover and connect with Chromecast devices
version: 1.1.1
homepage: https://github.com/jonathantribouharet/flutter_cast

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  bonsoir: ^3.0.0+1
  flutter:
    sdk: flutter
  multicast_dns: ^0.3.2+4
  protobuf: ^3.1.0

dev_dependencies:
  pedantic: ^1.11.1
  protoc_plugin: ^21.1.1
